### PR TITLE
Set up a "Hello world" project with two apps

### PR DESCRIPTION
**Pull request by zeff96**
- [ ]     Created a new Rails API app called 'hello-rails-back-end'.
- [ ]     Created a table for storing my messages and create 5 different greetings.
- [ ]     Created an API endpoint that selects a random greeting from your table (you will need a controller with an action and rails 
route).

### CODE REVIEW

**Review by Ismailco — COMMENTED** [review]
Hi @zeff96, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no link to the front-end repo, kindly make sure to add it in the README file so it's accessible

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by zeff96** [comment]
@Ismailco, do i need to deploy the front end app?

**Comment by Ismailco** [comment]
@zeff96, You're not required to deploy the app, just make sure the README has a link to the front-end repo. I can't find any link to the second repo

**Comment by zeff96** [comment]
@Ismailco, If it is just the link the I added on both projects links to PR

**Comment by zeff96** [comment]
@Ismailco, have a look under the project set up you will find 
### Hello-react-front-end with pr to the front pull request

**Comment by Ismailco** [comment]
@zeff96, I didn't see it, I would suggest making it a link so it's different from the setup instructions

**Comment by zeff96** [comment]
@Ismailco, ok

**Review by addod19 — APPROVED** [review]
### Hi @zeff96, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights
- [ ] Correct Git-flow followed :100: 
- [ ] Routes and controller action created :rocket: 
- [ ] Migration and model created as expected :fireworks: 
- [ ] 5 different messages created in console successfully :1st_place_medal: 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by addod19** [comment]
@zeff96 kindly take note of the front end and make the changes. Back-end approved doesn't mean the front-end is approved

**Comment by zeff96** [comment]
@addod19, Thanks for the approval

**Pull request merged**
